export const areas = [
  {
    id: 194,
    idzona: 194,
    name: "AREA - Contra plagas e incendios",
    code: null,
  },
  {
    id: 189,
    idzona: 189,
    name: "AREA - Control de Incendios",
    code: null,
  },
  {
    id: 188,
    idzona: 188,
    name: "AREA - Control de Plagas",
    code: null,
  },
  {
    id: 691,
    idzona: 691,
    name: "AREA - Control de plagas e incendios.",
    code: null,
  },
  {
    id: 684,
    idzona: 684,
    name: "AREA - Corporativo CDMX",
    code: null,
  },
  {
    id: 185,
    idzona: 185,
    name: "AREA - Cosecha Eucalipto",
    code: null,
  },
  {
    id: 680,
    idzona: 680,
    name: "AREA - Cosecha Melina",
    code: null,
  },
  {
    id: 184,
    idzona: 184,
    name: "AREA - Cosecha Teca",
    code: null,
  },
  {
    id: 183,
    idzona: 183,
    name: "AREA - Forestal Eucalipto",
    code: null,
  },
  {
    id: 679,
    idzona: 679,
    name: "AREA - Forestal Melina",
    code: null,
  },
  {
    id: 176,
    idzona: 176,
    name: "AREA - Forestal Teca",
    code: null,
  },
  {
    id: 191,
    idzona: 191,
    name: "AREA - Inventario",
    code: null,
  },
  {
    id: 190,
    idzona: 190,
    name: "AREA - Investigaciones",
    code: null,
  },
  {
    id: 196,
    idzona: 196,
    name: "AREA - Mantenimiento Mecánico",
    code: null,
  },
  {
    id: 195,
    idzona: 195,
    name: "AREA - Planificación",
    code: null,
  },
  {
    id: 186,
    idzona: 186,
    name: "AREA - Planta MDF",
    code: null,
  },
  {
    id: 681,
    idzona: 681,
    name: "AREA - Recursos Humanos",
    code: null,
  },
  {
    id: 683,
    idzona: 683,
    name: "AREA - Seguridad Patrimonial",
    code: null,
  },
  {
    id: 682,
    idzona: 682,
    name: "AREA - Seguridad, Higiene y Ambiente",
    code: null,
  },
  {
    id: 193,
    idzona: 193,
    name: "AREA - Vivero Choapas",
    code: null,
  },
];
