export const sidebarList = [
  {
    id: 1,
    show: true,
    name: "Inicio",
    icon: "ri-home-2-line",
    link: "/dashboard",
    submenu: [],
    active: true,
  },
  {
    id: 2,
    show: true,
    name: "Tarjetas",
    icon: "ri-bank-card-line",
    link: "/cards",
    submenu: [
      {
        id: 1,
        name: "Historial",
        link: "/history",
      },
      {
        id: 2,
        name: "Nueva comprobación",
        link: "/create-comprobation",
      },
    ],
    active: false,
  },
  {
    id: 3,
    show: true,
    name: "Equipos",
    icon: "ri-truck-line",
    link: "/machines",
    submenu: [],
    active: false,
  },
  {
    id: 4,
    show: true,
    name: "Ordenes de trabajo",
    icon: "ri-file-settings-line",
    link: "/job-orders",
    submenu: [],
    active: false,
  },
  {
    id: 5,
    show: true,
    name: "Pedidos",
    icon: "ri-archive-stack-line",
    link: "/orders",
    submenu: [
      {
        id: 1,
        name: "Ordenes de compra",
        link: "",
      },
      {
        id: 2,
        name: "Solicitudes de pedidos",
        link: "/requests",
      },
    ],
    active: false,
  },
  {
    id: 6,
    show: true,
    name: "Centros de costo",
    icon: "ri-money-dollar-circle-line",
    link: "/cecos",
    submenu: [],
    active: false,
  },
  {
    id: 7,
    show: true,
    name: "Alertas",
    icon: "ri-error-warning-line",
    link: "/",
    submenu: [],
    active: false,
  },
];
