export const sidebarList = [
  {
    id: 1,
    show: true,
    name: "Inicio",
    icon: "ri-home-2-line",
    link: "/panel",
    submenu: [],
    active: true,
  },
  // {
  //   id: 2,
  //   show: true,
  //   name: "Tarjetas",
  //   icon: "ri-bank-card-line",
  //   link: "/cards",
  //   submenu: [
  //     {
  //       id: 1,
  //       name: "Historial",
  //       link: "/history",
  //     },
  //     {
  //       id: 2,
  //       name: "Nueva comprobación",
  //       link: "/create-comprobation",
  //     },
  //   ],
  //   active: false,
  // },
  {
    id: 3,
    show: true,
    name: "Equipos",
    icon: "ri-truck-line",
    link: "/maquinas",
    submenu: [],
    active: false,
  },
  {
    id: 4,
    show: true,
    name: "Ordenes de trabajo",
    icon: "ri-file-settings-line",
    link: "/ordenes-de-trabajo",
    submenu: [],
    active: false,
  },
  {
    id: 5,
    show: true,
    name: "Pedidos",
    icon: "ri-archive-stack-line",
    link: "/ordenes",
    submenu: [
      {
        id: 1,
        name: "Ordenes de compra",
        link: "",
      },
      {
        id: 2,
        name: "Solicitudes de pedidos",
        link: "/solicitudes",
      },
    ],
    active: false,
  },
  {
    id: 6,
    show: true,
    name: "Centros de costo",
    icon: "ri-money-dollar-circle-line",
    link: "/cecos",
    submenu: [],
    active: false,
  },
  {
    id: 7,
    show: true,
    name: "Hoja de vida",
    icon: "ri-money-dollar-circle-line",
    link: "/hoja-de-vida-equipos",
    submenu: [],
    active: false,
  },
  {
    id: 8,
    show: true,
    name: "Hojas de uso",
    icon: "ri-file-history-line",
    link: "/hoja-de-uso",
    submenu: [],
    active: false,
  },
  {
    id: 9,
    show: true,
    name: "Alertas",
    icon: "ri-error-warning-line",
    link: "/",
    submenu: [],
    active: false,
  },
];
